apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    app: jenkins-build
    version: 1.0v
    workLoad: multi-container
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: payload
            operator: In
            values:
            - automation
            - operation 
            - management
  containers:
    - name: helm
      image: lachlanevenson/k8s-helm:v3.2.4
      tty: true
      command:
        - cat